apiVersion: apps/v1
kind: Deployment
metadata:
  name: tree-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 363894962876.dkr.ecr.us-east-1.amazonaws.com/tree-repo:latest
          ports:
            - containerPort: 8080