version: "3.9.10"
services:
  web:
    # replace username/repo:tag with your name and image details
  image: 363894962876.dkr.ecr.us-east-1.amazonaws.com/tree-image:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: 1
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"